@baseUrl=http://localhost:3000
@contentType=application/json
@tokenOwner=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAwMTE1MzA2LCJleHAiOjE2MDI3MDczMDZ9.SfKMtN39bw8O3eQTMe3k4Cg4AiPay69TG7_c6aAgj8s
@tokenUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjAwMTE0MDQxLCJleHAiOjE2MDI3MDYwNDF9.BGDVUEr-00hJ7pZ1DWma-JhCCjAM8VP_85CxBcejOss
@refreshTokenOwner=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAwMTEyOTk2LCJleHAiOjE2MDI3MDQ5OTZ9.40ilnppsE49jWg6XRZgICZgApZzkXUnvJq2ApW2kB9A

@refreshTokenUser=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjAwMDI0NjcwLCJleHAiOjE2MDI2MTY2NzB9.xI2_plo3zAyEqrt86_OePyA_Qi6JwWd8fgtf2Fywfi4

### Create Company
POST {{baseUrl}}/create-company
Content-Type: {{contentType}}

{
  "name": "JoaoCorp",
  "description": "Testtestest",
  "owner": {
    "name": "João Bueno Cesário",
    "email": "joao@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678"
  }
}

### Create User (Sign Up)
POST {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
    "name": "Aldair",
    "email": "aldair@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678",
    "idCompany": 1
}

### Login User Owner (Sign In)
POST {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
  "email": "lucas@gmail.com",
  "password": "12345678"
}

### Login User without being Owner (Sign In)
POST {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}

{
  "email": "ze@gmail.com.br",
  "password": "12345678"
}

### Refresh Token
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}
Authorization: Bearer {{refreshTokenUser}}

### Edit Company
PUT {{baseUrl}}/company/1
Content-Type: {{contentType}}
Authorization: Bearer {{tokenOwner}}

{
  "name": "LucasBueno Corp",
  "description": "Testing description update."
}

### Edit User
PUT {{baseUrl}}/user/5
Content-Type: {{contentType}}
Authorization: Bearer {{tokenOwner}}

{
  "name": "Zé",
  "email": "ze@gmail.com.br"
}

### Delete User
DELETE {{baseUrl}}/user/5
Content-Type: {{contentType}}
Authorization: Bearer {{tokenOwner}}

### Create Role
POST {{baseUrl}}/role
Content-Type: {{contentType}}
Authorization: Bearer {{tokenOwner}}

{
  "name": "HUE",
  "description": "Chefe filosófico da empresa."
}